### ISSUE TITLE
Friends/Followers endpoint not working?

### ISSUE THREAD

**Issue by noqcks** [xboxapi/Xbox-One-API-Issues#16]
When I hit the friends endpoint for my xuid -- `https://xboxapi.com/v2/2533274977441620/friends` –- I keep getting the following error:

```
{
code: 8,
source: "Profile",
description: "The body of the request was invalid.",
traceInformation: null
}
```

What am I doing wrong? @djekl

**Comment by djekl** [comment]
@noqcks You aren't doing anything wrong, it looks like that user has privacy settings set to not allow you to see friends - https://account.xbox.com/en-US/Profile?GamerTag=Hale%20Infinity (View as account on XboxAPI, or as somebody who isn't a friend)

![Hale Infinity Profile](http://f.cl.ly/items/1k2Q290G313a0K0S0f04/Image%202016-01-30%20at%208.47.48%20am.png)
