### ISSUE TITLE
Login to Xbox Live not working

### ISSUE THREAD

**Issue by danielvetromilla** [xboxapi/Xbox-One-API-Issues#17]
I can't login via xboxapi.com to Xbox Live (oAuth and non-oAuth versions)

If i try to login to Xbox Live using oAuth (Sign in to Xbox LIVE using oAuth button), i get a redirect to https://xboxapi.com/xbox/oauth/authorize saying "The page you were looking doesn't exist (404)"

If i try to login to Xbox Live (Sign in to Xbox LIVE button), the button label changes to "Attempting login" but nothing happens.

![non-oauth](https://cloud.githubusercontent.com/assets/6577533/12853488/6c7bf0bc-cc1b-11e5-8374-516f5d0098dc.png)
![oauth](https://cloud.githubusercontent.com/assets/6577533/12853489/6c7cbe0c-cc1b-11e5-91f5-4565360f8060.png)

**Comment by djekl** [comment]
I don't understand how you are getting any issues with the oAuth approach to a login. None of the mapped endpoints have any 404 redirects on them. Please visit this URL to see if you have the XboxAPI app authorized on your account - https://account.live.com/Consent/Edit?client_id=00000000441701D6

If you do, please remove the permissions and attempt an oAuth login again by visiting this URL - xboxapi.com/xbox/oauth

If you aren't logged in you will be prompted to, then redirected to the Microsoft site asking you to long and authorize the app.

With regards to the none oAuth version (on the site itself), this can fail for many reasons. Some of which are if you have 2 factor auth on your account, or Microsoft blocking the IP address from a login.

**Comment by danielvetromilla** [comment]
After removing the permissions and trying to login (oAuth) seemed to work.
Thanks
