### ISSUE TITLE
Large numbers overflow

### ISSUE THREAD

**Issue by iBotPeaches** [xboxapi/Xbox-One-API-Issues#18]
Using the `gamercard` endpoint we encountered a user with a large number in his profile.

```
114488473374406262982
```
Above is what we see on his profile on xbox.com.

XboxAPI returns

```
"bio":1.1448847337441e+20
```

I believe the expected content should treat everything as a string.

Thanks for the research by @gmsteuart

**Comment by djekl** [comment]
Do you have the users XUID or Gamertag?

**Comment by iBotPeaches** [comment]
`2568124073236624` there is xuid.

**Comment by djekl** [comment]
This issue is now resolved

**Comment by iBotPeaches** [comment]
sweet! thanks for quick fix!

**Comment by GMSteuart** [comment]
This is incredible!
