### ISSUE TITLE
Where to find Game ID in HEX or Game Product ID

### ISSUE THREAD

**Issue by igorissen** [xboxapi/Xbox-One-API-Issues#19]
Hi,

I start testing your API and I found (maybe) an issue. I can't find the Game ID in HEX (`https://xboxapi.com/v2/game-details-hex/587BDAF2`) or Game Product ID (`https://xboxapi.com/v2/game-details/9bf4c4be-71b2-41c6-bcc2-d61ac057e2f2`) when requesting my Xbox One or Xbox 360 games list. This is an example of the requests

* Xbox 360

```json
{
  "lastPlayed": "2016-05-16T19:47:44.8430000Z",
  "currentAchievements": 3,
  "currentGamerscore": 25,
  "sequence": 1196,
  "titleId": 1431505078,
  "titleType": 1,
  "platforms": [
    1
  ],
  "name": "SplinterCell Blacklist",
  "totalAchievements": 47,
  "totalGamerscore": 1000
}
```

* Xbox One

```json
{
  "lastUnlock": "2016-01-03T15:01:21.5807320Z",
  "titleId": 58472989,
  "serviceConfigId": "5af40b00-965f-4a28-aab5-cf69642bec88",
  "titleType": "DGame",
  "platform": "Durango",
  "name": "Killer Instinct",
  "earnedAchievements": 8,
  "currentGamerscore": 60,
  "maxGamerscore": 3835
}
```

How can I get these IDs ?

Thank you.

**Comment by djekl** [comment]
Hi, take the `titleId` and convert it from an integer into Hexidecimal
