### ISSUE TITLE
Add 'ProductId' and/or 'HexTitleId' to endpoints #23, #24 (user games)

### ISSUE THREAD

**Issue by SLiX69** [xboxapi/Xbox-One-API-Issues#22]
Hi, is it possible to add 'ProductId' to output of endpoints #23 (/v2/{xuid}/xbox360games) and #24 '(/v2/{xuid}/xboxonegames)?

I would like to get some additional infos about user games (eg pictures and description)

**Comment by djekl** [comment]
Just take the `titleId` that is an integer and convert that to hexidecimal. You can do this in many languages natively, for example PHP has `dechex()`

**Comment by SLiX69** [comment]
I 'accidentaly' wrote the answer in the title, but I wanted to ask about gameId (or hex gameId). Endpoint #26 says it needs gameId in hex, did not know gameId = titleId. 
It think it would be better to change API Documentation and mention that titleId (hex) can be used, instead of gameId
