### ISSUE TITLE
Outdated pagination docs?

### ISSUE THREAD

**Issue by forrestab** [xboxapi/Xbox-One-API-Issues#23]
In the _Pagination_ section of the documentation it says the `continuationToken` can be found in the response headers of some requests. But it looks like that is not the case anymore, at least for `/v2/{xuid}/activity`. Instead it looks like it comes in the response as the field `contToken`. 
Also, the query string field that you pass in with your next request says it should be `continuationToken`, but `contToken` works here instead.

**Comment by djekl** [comment]
Thanks for pointing that out, will get this fixed and inline with the documentation. You will still see the `contToken` in the response, but also in the headers as per docs. I will be leaving the current functionality in place for any others using it.

**Comment by djekl** [comment]
Closing as this is now brought inline with the docs
