### ISSUE TITLE
Support for clubs

### ISSUE THREAD

**Issue by voidpirate** [xboxapi/Xbox-One-API-Issues#24]
See Issue here. 

https://github.com/xboxapi/Python-Wrapper/issues/16

**Comment by djekl** [comment]
I have some of the Club endpoints mapped out already, I just need to find the time to finish mapping them all, and add it to the API. Will leave this issue open until I have it coded up.

**Comment by SweatyCubes** [comment]
How's everything coming along with Club Support? I also need this to be a thing. Was going to email you it as an idea until I saw this.

**Comment by djekl** [comment]
I have most of them mapped out, just need to add them to the site and get a full list of all available tags to search by

**Comment by SweatyCubes** [comment]
Thanks for taking the time to reply to me. I'll keep checking the Documentation page when I can but please let me know when it's up if it's not too much trouble.

**Comment by djekl** [comment]
I will be updating this when they are ready

**Comment by djekl** [comment]
I am pushing an update to the API now with the following new Club endpoints. More details are required to map out remaining endpoints, and all available tags for clubs (to search by)

| id | uri | name | description |
| --- | --- | --- | --- |
| 39 | https://xboxapi.com/v2/clubs/owned | Clubs I Own | Show clubs that you are an owner of |
| 40 | https://xboxapi.com/v2/clubs/joined | Clubs I Have Joined | Show clubs that you have joined - Note that the XUID is optional |
| 41 | http://xboxapi.dev/v2/clubs/details/3379884065497744 | Club Details | Show all information about a club |
| 42 | https://xboxapi.com/v2/clubs/search/name/XboxAPI | Search For Club By Name | You search for clubs by name |
| 43 | http://xboxapi.dev/v2/clubs/search/titles/219630713,558797228 | Search For Club By Titles | You search for clubs by title id's (comma seperated for multiple) |
| 44 | http://xboxapi.dev/v2/clubs/search/tags/micrequired,textchatrequired | Search For Club By Tags | You search for clubs by tag's (comma seperated for multiple) - Note that not all tags are known |

**Comment by SweatyCubes** [comment]
For Club details: This site can’t be reached

This site on the company, organization or school intranet has the same URL as an external website. 

Try contacting your system administrator.
ERR_ICANN_NAME_COLLISION

Just so you know. The main thing I am hoping you could add is posting to a Clubs Activity Feed. I think it would be a cool feature.

**Comment by djekl** [comment]
fixed those dev links

**Comment by SweatyCubes** [comment]
I'm not sure if you know or not but `/v2/{xuid}/activity` only seems to get `Game Clips`, `Achievements` and `Followers`(The activity that says who you followed/added). It doesn't seems to get `Screenshots`. Are you planning on mapping out one to `Post to Club Activity Feed` and `Get all members of a Club`? If so, take your time. Please let me know if you are or not. Thanks.

**Comment by djekl** [comment]
Club activity is locked at the moment to the new auth that I am unable to crack

**Comment by SweatyCubes** [comment]
Crack as in trying to gain access to or crack as in you have access but can't seem to use that access to do any functions with? Aren't you using the Xbox Exclusive Dev API available to people who are a part of Xbox@ID?

**Comment by djekl** [comment]
crack as in reverse engineer the new authentication method that gives a longer access token and access to the new endpoints, or more data on existing ones

**Comment by SweatyCubes** [comment]
Okay. Good luck and take your time. Thanks.

**Comment by SweatyCubes** [comment]
How's the progress for Club Support?

**Comment by djekl** [comment]
@SweatyCubes there are already some club endpoints available, as per the docs. The rest are stuck behind the new auth that I haven't had the time to look into as much as I would like
