### ISSUE TITLE
Parameters for only certain achievement IDs

### ISSUE THREAD

**Issue by kakitzmiller** [xboxapi/Xbox-One-API-Issues#25]
I apologize if this is something fairly straightforward about APIs, but I did want to know if there was a possibility for me to send a parameter of IDs that I wanted to get with achievements.  

I tried adding query string parameters like ?id=109 and such, but I've not had any luck.  I'm fairly new to gathering API information, so thank you in advance for bearing with me.

**Comment by djekl** [comment]
Hey, sorry for not getting back sooner. I don't fully understand what you are wanting? We don't offer an endpoint for details on a specific achievement for a game.

Please look at teh docs for all available endpoints.

**Comment by kakitzmiller** [comment]
Sure thing.  Since I'm new to APIs, I didn't know if there was a way to generically narrow down the results.  I've been trying to find answers online, but hadn't found any.  Thanks for the input, I'm good closing this.  Figured it was worth a shot to ask!

**Comment by djekl** [comment]
Hey, thats not a problem, you aren't the idiot if you are willing to ask a question, its the idiot who doesn't ask the questions!
