### ISSUE TITLE
Unable to sign in through Microsoft account

### ISSUE THREAD

**Issue by electricman226** [xboxapi/Xbox-One-API-Issues#27]
When using the **'Login in'** feature:
The page hangs, with the sign in button text staying at *'Attempting login...'*

When using **OAuth**:
I am redirected to a 404 page after OAuth authorization (https://xboxapi.com/xbox/oauth/authorize).

Is there any possible way I may be able to use this API correctly?

**EDIT 1**: I have attempted the instructions for OAuth in #17 , but it still sends me to a 404 page (https://xboxapi.com/xbox/oauth/authorize)

**Comment by djekl** [comment]
@electricman226 until I can get this fixed, please email support@ to get this resolved manually

**Comment by djekl** [comment]
Closing this for now, issue should be resolved
