### ISSUE TITLE
Response format

### ISSUE THREAD

**Issue by igorissen** [xboxapi/Xbox-One-API-Issues#30]
Hi,

I'm currently testing your api with an HTTP client and I saw that not all responses are in JSON (`/xuid/{gamertag}` returns data of type `text`).

Is it a normal?

Best regards

**Comment by djekl** [comment]
Hi, yes, and it is also valid json.

**Comment by igorissen** [comment]
For me it will not work. I want to create a wrapper using Node.js and It'll not work

```
▶ node
> JSON.parse('Fluxb0x')
SyntaxError: Unexpected token F in JSON at position 0
```

The response will have the header `Content-Type` set to  `text/plain` so that the http client will not parse the response body and it will be my responsability to handle this scenario.

**Comment by djekl** [comment]
Your application isn't requesting JSON, if you send the header `Accept: application/json`, then the response headers will be `application/json`.

With your example, you are using a simple string, but in your first message you are talking about the `XUID` endpoint, which will return an integer. This is valid JSON, but with the `Gamertag` endpoint, when requested correctly with `Accept: application/json`, then you will get a valid JSON response.

You should always be sending an `Accept` header to any API, not just this one.

**Comment by igorissen** [comment]
I just tried and it work.

Thank you.
