### ISSUE TITLE
All endpoints aren't protected

### ISSUE THREAD

**Issue by igorissen** [xboxapi/Xbox-One-API-Issues#33]
Hi,

I just saw that this request doesn't require `X-AUTH`

[https://xboxapi.com/v2/2533274842051692/screenshot-details/d1adc8aa-0a31-4407-90f2-7e9b54b0347c/6f5cd3a9-c4fc-4d16-ba31-1a0f774f3819](https://xboxapi.com/v2/2533274842051692/screenshot-details/d1adc8aa-0a31-4407-90f2-7e9b54b0347c/6f5cd3a9-c4fc-4d16-ba31-1a0f774f3819)

Is it normal?

**Comment by djekl** [comment]
If you are logged into XboxAPI then requests can be made without API tokens, to test open private browsing and attempt to view the screenshot there
