### ISSUE TITLE
Auth expiry

### ISSUE THREAD

**Issue by robhuzzey** [xboxapi/Xbox-One-API-Issues#35]
I've written a cronjob to fetch data every hour & the auth token (from xbox live) is running out eeach day.

Is there a way to refresh this token with your api at all?

**Comment by djekl** [comment]
If you are making requests every hour, then the tokens are lasting as long as they can be with refreshing. If you are using the oAuth login, these can't be refreshed any further than ~24 hours.

The best method is to save your password with us, this encrypts your password, with an encryption key that is uniquely and programmatically generated against your account. We can then re-authenticate your account when needed.

If you enable Pushover, you will be notified of these events.

**Comment by robhuzzey** [comment]
@djekl thanks.... I did save the password with you... but still was using OAuth. I presume I need to login without OAuth & then save details?

What is pushover? And when I am notified, am I able to re-authenticate programatically?

**Comment by djekl** [comment]
@robhuzzey here is where you went wrong m8

![Image](https://cl.ly/0t2a361q431P/download/[fe433344455d340f73d2112e90780b13]_Image%25202017-08-30%2520at%25205.54.10%2520pm.png)

Also, here is [Pushover](https://pushover.net/), its an app you install on your phone, and you enter your key on the [settings page](https://xboxapi.com/profile/edit)

![Image](https://cl.ly/13052H1f3J2G/download/Image%202017-08-30%20at%206.02.31%20pm.png)

**Comment by robhuzzey** [comment]
@djekl lol... yeah... it's obvious now ;) Thanks... I will give pushover a go too... looks really cool.
