### ISSUE TITLE
Expand xboxonegames and xbox360games endpoints

### ISSUE THREAD

**Issue by marcreichel** [xboxapi/Xbox-One-API-Issues#36]
Hi there,

Thank you for this really great API :)

I have a little Issue:
The endpoints `/v2/{xuid}/xboxonegames` and `/v2/{xuid}/xbox360games` only return games where the user has gamerscore. Could this be changed so these endpoints return all games a user has ever purchased (or started). I want to use these lists of games to verify a user can create an event for a specific game on our website. If the user owns the game he can create an event. But at the moment the user might only create events for games where he has gamerscore.

Thanks :)

**Comment by djekl** [comment]
Hey @marcreichel,

The data that I provide is 99% direct from Microsoft, XboxAPI is (in the simplest of terms) an easy to use wrapper for the official API Microsoft use within the Xbox Mobile and Desktop apps. Because of this I am not able to modify the returned data to that extent.

**Comment by marcreichel** [comment]
Hm. Okay.
Thanks anyways :)

**Comment by ReddHerring** [comment]
Hey, for this question I wrote an workaround in the xbox-wrapper repository. Cause I have the same problem ;)
