### ISSUE TITLE
Missing Games?

### ISSUE THREAD

**Issue by marcreichel** [xboxapi/Xbox-One-API-Issues#37]
Hi there again,

what's the reason the API does not provide information for all games? Does Microsoft simply do not return these data? I just tried to look up game information for title_id `1999574456` (Which should be Forza Motorsport 7) but the API did not return any results. Forza Motorsport 7 is also missing in the `browse-marketplace` endpoint.

**Comment by djekl** [comment]
Hey @marcreichel,

This is an issue with the endpoint I am using from Microsoft, and the version of auth that we use. I have been doing work on these issues, but as of yet am unsuccessful at the moment.

**Comment by marcreichel** [comment]
Okay. Let me know when this is fixed :)

**Comment by MChartier** [comment]
Are there any updates on this? I am able to retrieve data for Forza Motorsport 7, but Sea of Thieves (perhaps among others?) is missing.

**Comment by djekl** [comment]
Hey @MChartier as per the email I have sent in reply to yours. I will be hopefully looking into this over the weekend again. With the recent deprication of the smartglass app, a lot of endpoints are now dead and replacements need to be found. This is something I am working on, and am also working on the new authentication process to gain access to further endpoints not currently available.
