### ISSUE TITLE
Missing progression on achievement

### ISSUE THREAD

**Issue by kodekassen** [xboxapi/Xbox-One-API-Issues#39]
Game: Gears of War 4
TitleId: 552499398
AchievementID: 157

curl -i -H "X-AUTH: {apikey}" https://xboxapi.com/v2/{xuid}/achievements/552499398

On every object the "current" has a value of "null" instead of the actual value. The actual values is present when doing a data-dump from the xbox app. I would be super nice to see this fixed ^_^

**Comment by djekl** [comment]
This is an issue with the current auth we are using on XboxAPI, until I can crack the new one, not all games have achievement progress unfortunately.

**Comment by kodekassen** [comment]
I thought so ... i've actually working on the exact same problem myself :P
