### ISSUE TITLE
Hidden Rate Limit ({xuid}/presence)

### ISSUE THREAD

**Issue by iBotPeaches** [xboxapi/Xbox-One-API-Issues#40]
I've been on the free plan for almost 4 years now, just hitting the `{xuid}/presence` endpoint. I just loop and hit the 9 members in our clan, when someone in the clan requests who is online. It's cached pretty heavily so I stay under the 40 requests an hour limit.

So we just hit those 9 members presence endpoint. Worked fine since I developed it, but now it always fails with a "503" error. Running the request that failed works fine individually and the failure URL tends to be random among the 9 requests with 1 URL working 2 minutes ago, failing with 503 in a different iteration.

I patched my application to allow URLs to fail in the pool - https://github.com/iBotPeaches/PandaLove/commit/6a46c87d87e0fa6b6c784eca462ad462fd0843bf , but now if I send 9 requests only 3-4 actually send with the rest rejecting with status 503.

I re-authed the Xbox account with XboxAPI, using both OAuth and just flat out handing over my credentials to no avail. Is this some new rate limit imposed on the Xbox side? Since it doesn't seem to be a limited at the XboxAPI side.

**Comment by djekl** [comment]
@iBotPeaches just made over 100 requests all without issue. Looking at your code, you are making asynchronous requests. If you attempt to make too many requests in a short period of time, you will get timed out by Nginx, and cause issues with the server.

Here is my very basic PHP cURL script that makes synchronous requests for the presence of all my friends (or the friends of the account linked on XboxAPI).

```php
<?php

$api_key = "-=- CHANGEME -=-";

print PHP_EOL . "Fetching Friends" . PHP_EOL . PHP_EOL;

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://xboxapi.com/v2/me/friends");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    "X-Auth: {$api_key}",
]);

$response = curl_exec($ch);

if (!$response) {
    $error = curl_error($ch);
    $code = curl_errno($ch);
    curl_close($ch);

    print "Error: \"{$error}\"\n";
    print "Code: {$code}\n";
    exit;
}

echo "Response HTTP Status Code : " . curl_getinfo($ch, CURLINFO_HTTP_CODE) . PHP_EOL . PHP_EOL;
curl_close($ch);

print PHP_EOL . "----------------------------------------------------------------------------------------------------" . PHP_EOL;

array_walk(json_decode($response), function($friend) use ($api_key) {
    print "Fetching Presence of \"{$friend->Gamertag}\"" . PHP_EOL . PHP_EOL;
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://xboxapi.com/v2/{$friend->id}/presence");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "X-Auth: {$api_key}",
    ]);

    $response = curl_exec($ch);

    if (!$response) {
        $error = curl_error($ch);
        $code = curl_errno($ch);
        curl_close($ch);

        print "Error: \"{$error}\"\n";
        print "Code: {$code}\n";
        exit;
    }

    echo "Response HTTP Status Code : " . curl_getinfo($ch, CURLINFO_HTTP_CODE) . PHP_EOL . PHP_EOL;
    curl_close($ch);

    print json_encode(json_decode($response), JSON_PRETTY_PRINT) . PHP_EOL;
    print PHP_EOL . "----------------------------------------------------------------------------------------------------" . PHP_EOL . PHP_EOL;
});
```

You can see it running without issue here - https://cl.ly/3J0F181D2j0o

There are no "hidden" api limits on the server. Also if you upgrade to a `Gold` or above account, you can request the presence of multiple XUID's - https://gist.github.com/djekl/ac7187057aa96dd4a59e202c31654b94

Try the above snippet, and let me know how you get on. If you send me an email, we can arrange a higher limit for this testing.

**Comment by iBotPeaches** [comment]
Thanks for the detailed response and investigation. Just leaving a note to let you know I read it and will make some changes and report back (Moving to synchronous requests). Related, I was unaware of the ability to post multiple XUID's with Gold+ account.

**Comment by djekl** [comment]
Hey @iBotPeaches thats not a problem, the multiple XUID isn't documented on the site yet, I still need to do that, along with deprecate some endpoints that Microsoft have also deprecated, and put replacements up for them.

**Comment by iBotPeaches** [comment]
Thank you! It was indeed the async problem, not sure how I squeaked by all these years doing it that way. The script got a bit slower, because of the nature of the synchronous behavior, but it works so I'm happy. I'll close this out.

context: https://github.com/iBotPeaches/PandaLove/commit/376def292ceed815397355e2a980742be6d15581

**Comment by djekl** [comment]
I believe thats due to the recent server changes I have been implementing to accommodate the increase in server load. There has also been some DDoS attacks against the server, that I am attempting to mitigate.
