### ISSUE TITLE
Password change issue

### ISSUE THREAD

**Issue by AlexanderHagerman** [xboxapi/Xbox-One-API-Issues#46]
Hi,

Trying to change my password and email. I can't change my email or password without a card entered. I mark remove all cards because I don't want to add a credit card, and then it acts like I can submit the new email and password, but it doesn't stick.

Can you just delete my account and make it possible to request an account removal from the profile page?

Thanks

alex.hagerman@outlook.com

**Comment by djekl** [comment]
This is not the place for account support, please in future email support@xboxapi.com. I will close your account for you now.

**Comment by AlexanderHagerman** [comment]
Sorry for misunderstanding where to send this. Thank you for your help @djekl :bowing_man:
